module.exports = {
  IS: String.fromCharCode(0),
  SEND: String.fromCharCode(1),
  ECHO: String.fromCharCode(1),
  ETX: String.fromCharCode(3),
  EOT: String.fromCharCode(4),
  TTYPE: String.fromCharCode(24),
  EOR1: String.fromCharCode(25),
  MSDP: String.fromCharCode(69),
  MSSP: String.fromCharCode(70),
  MCCP2: String.fromCharCode(86),
  MCCP: String.fromCharCode(90),
  MXP: String.fromCharCode(91),
  ZMP: String.fromCharCode(93),
  EOR: String.fromCharCode(239),
  SE: String.fromCharCode(240),
  GA: String.fromCharCode(249),
  SB: String.fromCharCode(250),
  WILL: String.fromCharCode(251),
  WONT: String.fromCharCode(252),
  DO: String.fromCharCode(253),
  DONT: String.fromCharCode(254),
  IAC: String.fromCharCode(255),
  ATCP: String.fromCharCode(200),
  GMCP: String.fromCharCode(201),
  ESC: String.fromCharCode(27),
};

